//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_CustAcco.Web_Common.GeneralAppService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDao", Namespace="http://schemas.datacontract.org/2004/07/WsDatCustAcco_Dao.Global")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao))]
    public partial class BaseDao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte CodigoCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAnuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaModificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAnuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPModificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IndicadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion ResultadoEjecucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SesionActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SesionAnuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SesionIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SesionModificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAnuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioModificoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CodigoCompania {
            get {
                return this.CodigoCompaniaField;
            }
            set {
                if ((this.CodigoCompaniaField.Equals(value) != true)) {
                    this.CodigoCompaniaField = value;
                    this.RaisePropertyChanged("CodigoCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSesion {
            get {
                return this.CodigoSesionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSesionField, value) != true)) {
                    this.CodigoSesionField = value;
                    this.RaisePropertyChanged("CodigoSesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaActivo {
            get {
                return this.FechaActivoField;
            }
            set {
                if ((this.FechaActivoField.Equals(value) != true)) {
                    this.FechaActivoField = value;
                    this.RaisePropertyChanged("FechaActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAnulo {
            get {
                return this.FechaAnuloField;
            }
            set {
                if ((this.FechaAnuloField.Equals(value) != true)) {
                    this.FechaAnuloField = value;
                    this.RaisePropertyChanged("FechaAnulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaModifico {
            get {
                return this.FechaModificoField;
            }
            set {
                if ((this.FechaModificoField.Equals(value) != true)) {
                    this.FechaModificoField = value;
                    this.RaisePropertyChanged("FechaModifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPActivo {
            get {
                return this.IPActivoField;
            }
            set {
                if ((object.ReferenceEquals(this.IPActivoField, value) != true)) {
                    this.IPActivoField = value;
                    this.RaisePropertyChanged("IPActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAnulo {
            get {
                return this.IPAnuloField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAnuloField, value) != true)) {
                    this.IPAnuloField = value;
                    this.RaisePropertyChanged("IPAnulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPIngreso {
            get {
                return this.IPIngresoField;
            }
            set {
                if ((object.ReferenceEquals(this.IPIngresoField, value) != true)) {
                    this.IPIngresoField = value;
                    this.RaisePropertyChanged("IPIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPModifico {
            get {
                return this.IPModificoField;
            }
            set {
                if ((object.ReferenceEquals(this.IPModificoField, value) != true)) {
                    this.IPModificoField = value;
                    this.RaisePropertyChanged("IPModifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Indicador {
            get {
                return this.IndicadorField;
            }
            set {
                if ((this.IndicadorField.Equals(value) != true)) {
                    this.IndicadorField = value;
                    this.RaisePropertyChanged("Indicador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion ResultadoEjecucion {
            get {
                return this.ResultadoEjecucionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoEjecucionField, value) != true)) {
                    this.ResultadoEjecucionField = value;
                    this.RaisePropertyChanged("ResultadoEjecucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SesionActivo {
            get {
                return this.SesionActivoField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionActivoField, value) != true)) {
                    this.SesionActivoField = value;
                    this.RaisePropertyChanged("SesionActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SesionAnulo {
            get {
                return this.SesionAnuloField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionAnuloField, value) != true)) {
                    this.SesionAnuloField = value;
                    this.RaisePropertyChanged("SesionAnulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SesionIngreso {
            get {
                return this.SesionIngresoField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionIngresoField, value) != true)) {
                    this.SesionIngresoField = value;
                    this.RaisePropertyChanged("SesionIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SesionModifico {
            get {
                return this.SesionModificoField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionModificoField, value) != true)) {
                    this.SesionModificoField = value;
                    this.RaisePropertyChanged("SesionModifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioActivo {
            get {
                return this.UsuarioActivoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioActivoField, value) != true)) {
                    this.UsuarioActivoField = value;
                    this.RaisePropertyChanged("UsuarioActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioAnulo {
            get {
                return this.UsuarioAnuloField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAnuloField, value) != true)) {
                    this.UsuarioAnuloField = value;
                    this.RaisePropertyChanged("UsuarioAnulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioIngreso {
            get {
                return this.UsuarioIngresoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioIngresoField, value) != true)) {
                    this.UsuarioIngresoField = value;
                    this.RaisePropertyChanged("UsuarioIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioModifico {
            get {
                return this.UsuarioModificoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioModificoField, value) != true)) {
                    this.UsuarioModificoField = value;
                    this.RaisePropertyChanged("UsuarioModifico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoEjecucion", Namespace="http://schemas.datacontract.org/2004/07/WsDatCustAcco_Dao.Global")]
    [System.SerializableAttribute()]
    public partial class ResultadoEjecucion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorTecnicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorTecnico {
            get {
                return this.MensajeErrorTecnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorTecnicoField, value) != true)) {
                    this.MensajeErrorTecnicoField = value;
                    this.RaisePropertyChanged("MensajeErrorTecnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeErrorUsuario {
            get {
                return this.MensajeErrorUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorUsuarioField, value) != true)) {
                    this.MensajeErrorUsuarioField = value;
                    this.RaisePropertyChanged("MensajeErrorUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProveedorDao", Namespace="http://schemas.datacontract.org/2004/07/WsDatCustAcco_Dao.ModuloGeneral")]
    [System.SerializableAttribute()]
    public partial class ProveedorDao : WB_CustAcco.Web_Common.GeneralAppService.BaseDao {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> CodigoProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionEstadoProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoProveedorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliasProveedor {
            get {
                return this.AliasProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasProveedorField, value) != true)) {
                    this.AliasProveedorField = value;
                    this.RaisePropertyChanged("AliasProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> CodigoProveedor {
            get {
                return this.CodigoProveedorField;
            }
            set {
                if ((this.CodigoProveedorField.Equals(value) != true)) {
                    this.CodigoProveedorField = value;
                    this.RaisePropertyChanged("CodigoProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionEstadoProveedor {
            get {
                return this.DescripcionEstadoProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionEstadoProveedorField, value) != true)) {
                    this.DescripcionEstadoProveedorField = value;
                    this.RaisePropertyChanged("DescripcionEstadoProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoProveedor {
            get {
                return this.EstadoProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoProveedorField, value) != true)) {
                    this.EstadoProveedorField = value;
                    this.RaisePropertyChanged("EstadoProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProveedor {
            get {
                return this.NombreProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProveedorField, value) != true)) {
                    this.NombreProveedorField = value;
                    this.RaisePropertyChanged("NombreProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoProveedor {
            get {
                return this.TelefonoProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoProveedorField, value) != true)) {
                    this.TelefonoProveedorField = value;
                    this.RaisePropertyChanged("TelefonoProveedor");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneralAppService.IGeneralAppService")]
    public interface IGeneralAppService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/IngresarProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/IngresarProveedorResponse")]
        WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao IngresarProveedor(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/IngresarProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/IngresarProveedorResponse")]
        System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao> IngresarProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/EditarProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/EditarProveedorResponse")]
        WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao EditarProveedor(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/EditarProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/EditarProveedorResponse")]
        System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao> EditarProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/EliminarProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/EliminarProveedorResponse")]
        WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion EliminarProveedor(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/EliminarProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/EliminarProveedorResponse")]
        System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion> EliminarProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/ActivarProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/ActivarProveedorResponse")]
        WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion ActivarProveedor(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/ActivarProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/ActivarProveedorResponse")]
        System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion> ActivarProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/ObtenerProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/ObtenerProveedorResponse")]
        WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorResponse ObtenerProveedor(WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralAppService/ObtenerProveedor", ReplyAction="http://tempuri.org/IGeneralAppService/ObtenerProveedorResponse")]
        System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorResponse> ObtenerProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerProveedor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<byte> codigoProveedor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short codigoError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mensajeError;
        
        public ObtenerProveedorRequest() {
        }
        
        public ObtenerProveedorRequest(System.Nullable<byte> codigoProveedor, short codigoError, string mensajeError) {
            this.codigoProveedor = codigoProveedor;
            this.codigoError = codigoError;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerProveedorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao ObtenerProveedorResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short codigoError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mensajeError;
        
        public ObtenerProveedorResponse() {
        }
        
        public ObtenerProveedorResponse(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao ObtenerProveedorResult, short codigoError, string mensajeError) {
            this.ObtenerProveedorResult = ObtenerProveedorResult;
            this.codigoError = codigoError;
            this.mensajeError = mensajeError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralAppServiceChannel : WB_CustAcco.Web_Common.GeneralAppService.IGeneralAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralAppServiceClient : System.ServiceModel.ClientBase<WB_CustAcco.Web_Common.GeneralAppService.IGeneralAppService>, WB_CustAcco.Web_Common.GeneralAppService.IGeneralAppService {
        
        public GeneralAppServiceClient() {
        }
        
        public GeneralAppServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralAppServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralAppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralAppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao IngresarProveedor(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao) {
            return base.Channel.IngresarProveedor(solicitudDao);
        }
        
        public System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao> IngresarProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao) {
            return base.Channel.IngresarProveedorAsync(solicitudDao);
        }
        
        public WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao EditarProveedor(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao) {
            return base.Channel.EditarProveedor(solicitudDao);
        }
        
        public System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao> EditarProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao) {
            return base.Channel.EditarProveedorAsync(solicitudDao);
        }
        
        public WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion EliminarProveedor(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao) {
            return base.Channel.EliminarProveedor(solicitudDao);
        }
        
        public System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion> EliminarProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao) {
            return base.Channel.EliminarProveedorAsync(solicitudDao);
        }
        
        public WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion ActivarProveedor(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao) {
            return base.Channel.ActivarProveedor(solicitudDao);
        }
        
        public System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ResultadoEjecucion> ActivarProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao solicitudDao) {
            return base.Channel.ActivarProveedorAsync(solicitudDao);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorResponse WB_CustAcco.Web_Common.GeneralAppService.IGeneralAppService.ObtenerProveedor(WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorRequest request) {
            return base.Channel.ObtenerProveedor(request);
        }
        
        public WB_CustAcco.Web_Common.GeneralAppService.ProveedorDao ObtenerProveedor(System.Nullable<byte> codigoProveedor, ref short codigoError, ref string mensajeError) {
            WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorRequest inValue = new WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorRequest();
            inValue.codigoProveedor = codigoProveedor;
            inValue.codigoError = codigoError;
            inValue.mensajeError = mensajeError;
            WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorResponse retVal = ((WB_CustAcco.Web_Common.GeneralAppService.IGeneralAppService)(this)).ObtenerProveedor(inValue);
            codigoError = retVal.codigoError;
            mensajeError = retVal.mensajeError;
            return retVal.ObtenerProveedorResult;
        }
        
        public System.Threading.Tasks.Task<WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorResponse> ObtenerProveedorAsync(WB_CustAcco.Web_Common.GeneralAppService.ObtenerProveedorRequest request) {
            return base.Channel.ObtenerProveedorAsync(request);
        }
    }
}
